# Site settings
title: kolektiv (Andrew Cherry)
email: andrew@xyncro.com
description: "Blog"
baseurl: ""
url: "https://kolektiv.github.io"
twitter_username: kolektiv
github_username: kolektiv

# Build settings

encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

permalink: pretty
